version: '3.2'
services:
  db:
    image: postgres
    volumes:
      - phoenix-book-postgres:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
    command:
      - ./run.sh

volumes:
  phoenix-book-postgres:
    driver: local

